Repository WP-for-Church/Sermon-Manager, pull requests merged in 2018-06, with the labels that each got.

#211 Add support for custom WP Roles
  includes/admin/class-sm-admin-menus.php
  includes/class-sm-post-types.php
  includes/class-sm-roles.php
  readme.txt
  sermons.php
Labels: [Priority] Standard, [Type] Feature

#215 Add Podcast buttons
  .gitignore
  assets/css/partials/_shortcodes.scss
  assets/css/sermon.min.css
  assets/css/sermon.min.css.map
  includes/admin/settings/class-sm-settings-podcast.php
  includes/class-sm-shortcodes.php
  readme.txt
Labels: [Type] Feature

#217 Update ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: [Type] Meta
